//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.18046
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 原始程式碼已由 Microsoft.VSDesigner 自動產生，版本 4.0.30319.18046。
// 
#pragma warning disable 1591

namespace General.Service.COSS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="Service1Soap", Namespace="boss")]
    public partial class Service1 : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback BossGatewayOperationCompleted;
        
        private System.Threading.SendOrPostCallback ynDevOperationCompleted;
        
        private System.Threading.SendOrPostCallback sgMappingOperationCompleted;
        
        private System.Threading.SendOrPostCallback devClusterOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetSSLBasicPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAccWithPkgOperationCompleted;
        
        private System.Threading.SendOrPostCallback setUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback removeUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback setMasterOperationCompleted;
        
        private System.Threading.SendOrPostCallback CreateAccountOperationCompleted;
        
        private System.Threading.SendOrPostCallback sgToDeviceOperationCompleted;
        
        private System.Threading.SendOrPostCallback AddPackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback RemovePackageOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReadAccountSubscriberGroupsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAccountbyDeviceExternalIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback log_GetDeviceSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback log_GetUserOperationCompleted;
        
        private System.Threading.SendOrPostCallback AccountDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback log_getAccDetailsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDupSGOperationCompleted;
        
        private System.Threading.SendOrPostCallback xboxMPFOperationCompleted;
        
        private System.Threading.SendOrPostCallback stbToPurchaseOperationCompleted;
        
        private System.Threading.SendOrPostCallback QuanTuenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getMSWDSeqOperationCompleted;
        
        private System.Threading.SendOrPostCallback tttOperationCompleted;
        
        private System.Threading.SendOrPostCallback XMLsgMapping2cossOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public Service1() {
            this.Url = global::General.Service.Properties.Settings.Default.General_Service_COSS_MSTV_Service1;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event BossGatewayCompletedEventHandler BossGatewayCompleted;
        
        /// <remarks/>
        public event ynDevCompletedEventHandler ynDevCompleted;
        
        /// <remarks/>
        public event sgMappingCompletedEventHandler sgMappingCompleted;
        
        /// <remarks/>
        public event devClusterCompletedEventHandler devClusterCompleted;
        
        /// <remarks/>
        public event GetSSLBasicPackageCompletedEventHandler GetSSLBasicPackageCompleted;
        
        /// <remarks/>
        public event CreateAccWithPkgCompletedEventHandler CreateAccWithPkgCompleted;
        
        /// <remarks/>
        public event setUserCompletedEventHandler setUserCompleted;
        
        /// <remarks/>
        public event removeUserCompletedEventHandler removeUserCompleted;
        
        /// <remarks/>
        public event setMasterCompletedEventHandler setMasterCompleted;
        
        /// <remarks/>
        public event CreateAccountCompletedEventHandler CreateAccountCompleted;
        
        /// <remarks/>
        public event sgToDeviceCompletedEventHandler sgToDeviceCompleted;
        
        /// <remarks/>
        public event AddPackageCompletedEventHandler AddPackageCompleted;
        
        /// <remarks/>
        public event RemovePackageCompletedEventHandler RemovePackageCompleted;
        
        /// <remarks/>
        public event ReadAccountSubscriberGroupsCompletedEventHandler ReadAccountSubscriberGroupsCompleted;
        
        /// <remarks/>
        public event GetAccountbyDeviceExternalIdCompletedEventHandler GetAccountbyDeviceExternalIdCompleted;
        
        /// <remarks/>
        public event log_GetDeviceSGCompletedEventHandler log_GetDeviceSGCompleted;
        
        /// <remarks/>
        public event log_GetUserCompletedEventHandler log_GetUserCompleted;
        
        /// <remarks/>
        public event AccountDetailsCompletedEventHandler AccountDetailsCompleted;
        
        /// <remarks/>
        public event log_getAccDetailsCompletedEventHandler log_getAccDetailsCompleted;
        
        /// <remarks/>
        public event GetDupSGCompletedEventHandler GetDupSGCompleted;
        
        /// <remarks/>
        public event xboxMPFCompletedEventHandler xboxMPFCompleted;
        
        /// <remarks/>
        public event stbToPurchaseCompletedEventHandler stbToPurchaseCompleted;
        
        /// <remarks/>
        public event QuanTuenCompletedEventHandler QuanTuenCompleted;
        
        /// <remarks/>
        public event getMSWDSeqCompletedEventHandler getMSWDSeqCompleted;
        
        /// <remarks/>
        public event tttCompletedEventHandler tttCompleted;
        
        /// <remarks/>
        public event XMLsgMapping2cossCompletedEventHandler XMLsgMapping2cossCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/BossGateway", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string BossGateway(string cmd) {
            object[] results = this.Invoke("BossGateway", new object[] {
                        cmd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void BossGatewayAsync(string cmd) {
            this.BossGatewayAsync(cmd, null);
        }
        
        /// <remarks/>
        public void BossGatewayAsync(string cmd, object userState) {
            if ((this.BossGatewayOperationCompleted == null)) {
                this.BossGatewayOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBossGatewayOperationCompleted);
            }
            this.InvokeAsync("BossGateway", new object[] {
                        cmd}, this.BossGatewayOperationCompleted, userState);
        }
        
        private void OnBossGatewayOperationCompleted(object arg) {
            if ((this.BossGatewayCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BossGatewayCompleted(this, new BossGatewayCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/ynDev", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ynDev(string rc) {
            object[] results = this.Invoke("ynDev", new object[] {
                        rc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ynDevAsync(string rc) {
            this.ynDevAsync(rc, null);
        }
        
        /// <remarks/>
        public void ynDevAsync(string rc, object userState) {
            if ((this.ynDevOperationCompleted == null)) {
                this.ynDevOperationCompleted = new System.Threading.SendOrPostCallback(this.OnynDevOperationCompleted);
            }
            this.InvokeAsync("ynDev", new object[] {
                        rc}, this.ynDevOperationCompleted, userState);
        }
        
        private void OnynDevOperationCompleted(object arg) {
            if ((this.ynDevCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ynDevCompleted(this, new ynDevCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/sgMapping", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sgMapping(string id) {
            object[] results = this.Invoke("sgMapping", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sgMappingAsync(string id) {
            this.sgMappingAsync(id, null);
        }
        
        /// <remarks/>
        public void sgMappingAsync(string id, object userState) {
            if ((this.sgMappingOperationCompleted == null)) {
                this.sgMappingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsgMappingOperationCompleted);
            }
            this.InvokeAsync("sgMapping", new object[] {
                        id}, this.sgMappingOperationCompleted, userState);
        }
        
        private void OnsgMappingOperationCompleted(object arg) {
            if ((this.sgMappingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sgMappingCompleted(this, new sgMappingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/devCluster", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string devCluster(string cm) {
            object[] results = this.Invoke("devCluster", new object[] {
                        cm});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void devClusterAsync(string cm) {
            this.devClusterAsync(cm, null);
        }
        
        /// <remarks/>
        public void devClusterAsync(string cm, object userState) {
            if ((this.devClusterOperationCompleted == null)) {
                this.devClusterOperationCompleted = new System.Threading.SendOrPostCallback(this.OndevClusterOperationCompleted);
            }
            this.InvokeAsync("devCluster", new object[] {
                        cm}, this.devClusterOperationCompleted, userState);
        }
        
        private void OndevClusterOperationCompleted(object arg) {
            if ((this.devClusterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.devClusterCompleted(this, new devClusterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/GetSSLBasicPackage", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetSSLBasicPackage() {
            object[] results = this.Invoke("GetSSLBasicPackage", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetSSLBasicPackageAsync() {
            this.GetSSLBasicPackageAsync(null);
        }
        
        /// <remarks/>
        public void GetSSLBasicPackageAsync(object userState) {
            if ((this.GetSSLBasicPackageOperationCompleted == null)) {
                this.GetSSLBasicPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetSSLBasicPackageOperationCompleted);
            }
            this.InvokeAsync("GetSSLBasicPackage", new object[0], this.GetSSLBasicPackageOperationCompleted, userState);
        }
        
        private void OnGetSSLBasicPackageOperationCompleted(object arg) {
            if ((this.GetSSLBasicPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetSSLBasicPackageCompleted(this, new GetSSLBasicPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/CreateAccWithPkg", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateAccWithPkg(string acc, string rc, string telPwd) {
            object[] results = this.Invoke("CreateAccWithPkg", new object[] {
                        acc,
                        rc,
                        telPwd});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAccWithPkgAsync(string acc, string rc, string telPwd) {
            this.CreateAccWithPkgAsync(acc, rc, telPwd, null);
        }
        
        /// <remarks/>
        public void CreateAccWithPkgAsync(string acc, string rc, string telPwd, object userState) {
            if ((this.CreateAccWithPkgOperationCompleted == null)) {
                this.CreateAccWithPkgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAccWithPkgOperationCompleted);
            }
            this.InvokeAsync("CreateAccWithPkg", new object[] {
                        acc,
                        rc,
                        telPwd}, this.CreateAccWithPkgOperationCompleted, userState);
        }
        
        private void OnCreateAccWithPkgOperationCompleted(object arg) {
            if ((this.CreateAccWithPkgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAccWithPkgCompleted(this, new CreateAccWithPkgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/setUser", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setUser(string acc) {
            object[] results = this.Invoke("setUser", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setUserAsync(string acc) {
            this.setUserAsync(acc, null);
        }
        
        /// <remarks/>
        public void setUserAsync(string acc, object userState) {
            if ((this.setUserOperationCompleted == null)) {
                this.setUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetUserOperationCompleted);
            }
            this.InvokeAsync("setUser", new object[] {
                        acc}, this.setUserOperationCompleted, userState);
        }
        
        private void OnsetUserOperationCompleted(object arg) {
            if ((this.setUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setUserCompleted(this, new setUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/removeUser", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string removeUser(string acc) {
            object[] results = this.Invoke("removeUser", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void removeUserAsync(string acc) {
            this.removeUserAsync(acc, null);
        }
        
        /// <remarks/>
        public void removeUserAsync(string acc, object userState) {
            if ((this.removeUserOperationCompleted == null)) {
                this.removeUserOperationCompleted = new System.Threading.SendOrPostCallback(this.OnremoveUserOperationCompleted);
            }
            this.InvokeAsync("removeUser", new object[] {
                        acc}, this.removeUserOperationCompleted, userState);
        }
        
        private void OnremoveUserOperationCompleted(object arg) {
            if ((this.removeUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.removeUserCompleted(this, new removeUserCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/setMaster", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string setMaster(string acc) {
            object[] results = this.Invoke("setMaster", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void setMasterAsync(string acc) {
            this.setMasterAsync(acc, null);
        }
        
        /// <remarks/>
        public void setMasterAsync(string acc, object userState) {
            if ((this.setMasterOperationCompleted == null)) {
                this.setMasterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetMasterOperationCompleted);
            }
            this.InvokeAsync("setMaster", new object[] {
                        acc}, this.setMasterOperationCompleted, userState);
        }
        
        private void OnsetMasterOperationCompleted(object arg) {
            if ((this.setMasterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setMasterCompleted(this, new setMasterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/CreateAccount", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string CreateAccount(string acc) {
            object[] results = this.Invoke("CreateAccount", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void CreateAccountAsync(string acc) {
            this.CreateAccountAsync(acc, null);
        }
        
        /// <remarks/>
        public void CreateAccountAsync(string acc, object userState) {
            if ((this.CreateAccountOperationCompleted == null)) {
                this.CreateAccountOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateAccountOperationCompleted);
            }
            this.InvokeAsync("CreateAccount", new object[] {
                        acc}, this.CreateAccountOperationCompleted, userState);
        }
        
        private void OnCreateAccountOperationCompleted(object arg) {
            if ((this.CreateAccountCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateAccountCompleted(this, new CreateAccountCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/sgToDevice", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string sgToDevice(string pkgName) {
            object[] results = this.Invoke("sgToDevice", new object[] {
                        pkgName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void sgToDeviceAsync(string pkgName) {
            this.sgToDeviceAsync(pkgName, null);
        }
        
        /// <remarks/>
        public void sgToDeviceAsync(string pkgName, object userState) {
            if ((this.sgToDeviceOperationCompleted == null)) {
                this.sgToDeviceOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsgToDeviceOperationCompleted);
            }
            this.InvokeAsync("sgToDevice", new object[] {
                        pkgName}, this.sgToDeviceOperationCompleted, userState);
        }
        
        private void OnsgToDeviceOperationCompleted(object arg) {
            if ((this.sgToDeviceCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.sgToDeviceCompleted(this, new sgToDeviceCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/AddPackage", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AddPackage(string pkgName) {
            object[] results = this.Invoke("AddPackage", new object[] {
                        pkgName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AddPackageAsync(string pkgName) {
            this.AddPackageAsync(pkgName, null);
        }
        
        /// <remarks/>
        public void AddPackageAsync(string pkgName, object userState) {
            if ((this.AddPackageOperationCompleted == null)) {
                this.AddPackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAddPackageOperationCompleted);
            }
            this.InvokeAsync("AddPackage", new object[] {
                        pkgName}, this.AddPackageOperationCompleted, userState);
        }
        
        private void OnAddPackageOperationCompleted(object arg) {
            if ((this.AddPackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AddPackageCompleted(this, new AddPackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/RemovePackage", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string RemovePackage(string pkgName) {
            object[] results = this.Invoke("RemovePackage", new object[] {
                        pkgName});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RemovePackageAsync(string pkgName) {
            this.RemovePackageAsync(pkgName, null);
        }
        
        /// <remarks/>
        public void RemovePackageAsync(string pkgName, object userState) {
            if ((this.RemovePackageOperationCompleted == null)) {
                this.RemovePackageOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRemovePackageOperationCompleted);
            }
            this.InvokeAsync("RemovePackage", new object[] {
                        pkgName}, this.RemovePackageOperationCompleted, userState);
        }
        
        private void OnRemovePackageOperationCompleted(object arg) {
            if ((this.RemovePackageCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RemovePackageCompleted(this, new RemovePackageCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/ReadAccountSubscriberGroups", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string[] ReadAccountSubscriberGroups(string acc) {
            object[] results = this.Invoke("ReadAccountSubscriberGroups", new object[] {
                        acc});
            return ((string[])(results[0]));
        }
        
        /// <remarks/>
        public void ReadAccountSubscriberGroupsAsync(string acc) {
            this.ReadAccountSubscriberGroupsAsync(acc, null);
        }
        
        /// <remarks/>
        public void ReadAccountSubscriberGroupsAsync(string acc, object userState) {
            if ((this.ReadAccountSubscriberGroupsOperationCompleted == null)) {
                this.ReadAccountSubscriberGroupsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReadAccountSubscriberGroupsOperationCompleted);
            }
            this.InvokeAsync("ReadAccountSubscriberGroups", new object[] {
                        acc}, this.ReadAccountSubscriberGroupsOperationCompleted, userState);
        }
        
        private void OnReadAccountSubscriberGroupsOperationCompleted(object arg) {
            if ((this.ReadAccountSubscriberGroupsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReadAccountSubscriberGroupsCompleted(this, new ReadAccountSubscriberGroupsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/GetAccountbyDeviceExternalId", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetAccountbyDeviceExternalId(string dev) {
            object[] results = this.Invoke("GetAccountbyDeviceExternalId", new object[] {
                        dev});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetAccountbyDeviceExternalIdAsync(string dev) {
            this.GetAccountbyDeviceExternalIdAsync(dev, null);
        }
        
        /// <remarks/>
        public void GetAccountbyDeviceExternalIdAsync(string dev, object userState) {
            if ((this.GetAccountbyDeviceExternalIdOperationCompleted == null)) {
                this.GetAccountbyDeviceExternalIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAccountbyDeviceExternalIdOperationCompleted);
            }
            this.InvokeAsync("GetAccountbyDeviceExternalId", new object[] {
                        dev}, this.GetAccountbyDeviceExternalIdOperationCompleted, userState);
        }
        
        private void OnGetAccountbyDeviceExternalIdOperationCompleted(object arg) {
            if ((this.GetAccountbyDeviceExternalIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAccountbyDeviceExternalIdCompleted(this, new GetAccountbyDeviceExternalIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/log_GetDeviceSG", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string log_GetDeviceSG(string dev) {
            object[] results = this.Invoke("log_GetDeviceSG", new object[] {
                        dev});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void log_GetDeviceSGAsync(string dev) {
            this.log_GetDeviceSGAsync(dev, null);
        }
        
        /// <remarks/>
        public void log_GetDeviceSGAsync(string dev, object userState) {
            if ((this.log_GetDeviceSGOperationCompleted == null)) {
                this.log_GetDeviceSGOperationCompleted = new System.Threading.SendOrPostCallback(this.Onlog_GetDeviceSGOperationCompleted);
            }
            this.InvokeAsync("log_GetDeviceSG", new object[] {
                        dev}, this.log_GetDeviceSGOperationCompleted, userState);
        }
        
        private void Onlog_GetDeviceSGOperationCompleted(object arg) {
            if ((this.log_GetDeviceSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.log_GetDeviceSGCompleted(this, new log_GetDeviceSGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/log_GetUser", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void log_GetUser(string acc) {
            this.Invoke("log_GetUser", new object[] {
                        acc});
        }
        
        /// <remarks/>
        public void log_GetUserAsync(string acc) {
            this.log_GetUserAsync(acc, null);
        }
        
        /// <remarks/>
        public void log_GetUserAsync(string acc, object userState) {
            if ((this.log_GetUserOperationCompleted == null)) {
                this.log_GetUserOperationCompleted = new System.Threading.SendOrPostCallback(this.Onlog_GetUserOperationCompleted);
            }
            this.InvokeAsync("log_GetUser", new object[] {
                        acc}, this.log_GetUserOperationCompleted, userState);
        }
        
        private void Onlog_GetUserOperationCompleted(object arg) {
            if ((this.log_GetUserCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.log_GetUserCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/AccountDetails", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string AccountDetails(string acc) {
            object[] results = this.Invoke("AccountDetails", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void AccountDetailsAsync(string acc) {
            this.AccountDetailsAsync(acc, null);
        }
        
        /// <remarks/>
        public void AccountDetailsAsync(string acc, object userState) {
            if ((this.AccountDetailsOperationCompleted == null)) {
                this.AccountDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAccountDetailsOperationCompleted);
            }
            this.InvokeAsync("AccountDetails", new object[] {
                        acc}, this.AccountDetailsOperationCompleted, userState);
        }
        
        private void OnAccountDetailsOperationCompleted(object arg) {
            if ((this.AccountDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AccountDetailsCompleted(this, new AccountDetailsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/log_getAccDetails", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void log_getAccDetails(string acc) {
            this.Invoke("log_getAccDetails", new object[] {
                        acc});
        }
        
        /// <remarks/>
        public void log_getAccDetailsAsync(string acc) {
            this.log_getAccDetailsAsync(acc, null);
        }
        
        /// <remarks/>
        public void log_getAccDetailsAsync(string acc, object userState) {
            if ((this.log_getAccDetailsOperationCompleted == null)) {
                this.log_getAccDetailsOperationCompleted = new System.Threading.SendOrPostCallback(this.Onlog_getAccDetailsOperationCompleted);
            }
            this.InvokeAsync("log_getAccDetails", new object[] {
                        acc}, this.log_getAccDetailsOperationCompleted, userState);
        }
        
        private void Onlog_getAccDetailsOperationCompleted(object arg) {
            if ((this.log_getAccDetailsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.log_getAccDetailsCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/GetDupSG", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetDupSG(string accPlusSG) {
            object[] results = this.Invoke("GetDupSG", new object[] {
                        accPlusSG});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetDupSGAsync(string accPlusSG) {
            this.GetDupSGAsync(accPlusSG, null);
        }
        
        /// <remarks/>
        public void GetDupSGAsync(string accPlusSG, object userState) {
            if ((this.GetDupSGOperationCompleted == null)) {
                this.GetDupSGOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDupSGOperationCompleted);
            }
            this.InvokeAsync("GetDupSG", new object[] {
                        accPlusSG}, this.GetDupSGOperationCompleted, userState);
        }
        
        private void OnGetDupSGOperationCompleted(object arg) {
            if ((this.GetDupSGCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDupSGCompleted(this, new GetDupSGCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/xboxMPF", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string xboxMPF(string xboxMac) {
            object[] results = this.Invoke("xboxMPF", new object[] {
                        xboxMac});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void xboxMPFAsync(string xboxMac) {
            this.xboxMPFAsync(xboxMac, null);
        }
        
        /// <remarks/>
        public void xboxMPFAsync(string xboxMac, object userState) {
            if ((this.xboxMPFOperationCompleted == null)) {
                this.xboxMPFOperationCompleted = new System.Threading.SendOrPostCallback(this.OnxboxMPFOperationCompleted);
            }
            this.InvokeAsync("xboxMPF", new object[] {
                        xboxMac}, this.xboxMPFOperationCompleted, userState);
        }
        
        private void OnxboxMPFOperationCompleted(object arg) {
            if ((this.xboxMPFCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.xboxMPFCompleted(this, new xboxMPFCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/stbToPurchase", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string stbToPurchase(string accREC) {
            object[] results = this.Invoke("stbToPurchase", new object[] {
                        accREC});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void stbToPurchaseAsync(string accREC) {
            this.stbToPurchaseAsync(accREC, null);
        }
        
        /// <remarks/>
        public void stbToPurchaseAsync(string accREC, object userState) {
            if ((this.stbToPurchaseOperationCompleted == null)) {
                this.stbToPurchaseOperationCompleted = new System.Threading.SendOrPostCallback(this.OnstbToPurchaseOperationCompleted);
            }
            this.InvokeAsync("stbToPurchase", new object[] {
                        accREC}, this.stbToPurchaseOperationCompleted, userState);
        }
        
        private void OnstbToPurchaseOperationCompleted(object arg) {
            if ((this.stbToPurchaseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.stbToPurchaseCompleted(this, new stbToPurchaseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/QuanTuen", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string QuanTuen(string acc) {
            object[] results = this.Invoke("QuanTuen", new object[] {
                        acc});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void QuanTuenAsync(string acc) {
            this.QuanTuenAsync(acc, null);
        }
        
        /// <remarks/>
        public void QuanTuenAsync(string acc, object userState) {
            if ((this.QuanTuenOperationCompleted == null)) {
                this.QuanTuenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnQuanTuenOperationCompleted);
            }
            this.InvokeAsync("QuanTuen", new object[] {
                        acc}, this.QuanTuenOperationCompleted, userState);
        }
        
        private void OnQuanTuenOperationCompleted(object arg) {
            if ((this.QuanTuenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.QuanTuenCompleted(this, new QuanTuenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/getMSWDSeq", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string getMSWDSeq() {
            object[] results = this.Invoke("getMSWDSeq", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void getMSWDSeqAsync() {
            this.getMSWDSeqAsync(null);
        }
        
        /// <remarks/>
        public void getMSWDSeqAsync(object userState) {
            if ((this.getMSWDSeqOperationCompleted == null)) {
                this.getMSWDSeqOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetMSWDSeqOperationCompleted);
            }
            this.InvokeAsync("getMSWDSeq", new object[0], this.getMSWDSeqOperationCompleted, userState);
        }
        
        private void OngetMSWDSeqOperationCompleted(object arg) {
            if ((this.getMSWDSeqCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getMSWDSeqCompleted(this, new getMSWDSeqCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/ttt", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ttt() {
            object[] results = this.Invoke("ttt", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void tttAsync() {
            this.tttAsync(null);
        }
        
        /// <remarks/>
        public void tttAsync(object userState) {
            if ((this.tttOperationCompleted == null)) {
                this.tttOperationCompleted = new System.Threading.SendOrPostCallback(this.OntttOperationCompleted);
            }
            this.InvokeAsync("ttt", new object[0], this.tttOperationCompleted, userState);
        }
        
        private void OntttOperationCompleted(object arg) {
            if ((this.tttCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.tttCompleted(this, new tttCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("boss/XMLsgMapping2coss", RequestNamespace="boss", ResponseNamespace="boss", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string XMLsgMapping2coss(string id) {
            object[] results = this.Invoke("XMLsgMapping2coss", new object[] {
                        id});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void XMLsgMapping2cossAsync(string id) {
            this.XMLsgMapping2cossAsync(id, null);
        }
        
        /// <remarks/>
        public void XMLsgMapping2cossAsync(string id, object userState) {
            if ((this.XMLsgMapping2cossOperationCompleted == null)) {
                this.XMLsgMapping2cossOperationCompleted = new System.Threading.SendOrPostCallback(this.OnXMLsgMapping2cossOperationCompleted);
            }
            this.InvokeAsync("XMLsgMapping2coss", new object[] {
                        id}, this.XMLsgMapping2cossOperationCompleted, userState);
        }
        
        private void OnXMLsgMapping2cossOperationCompleted(object arg) {
            if ((this.XMLsgMapping2cossCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.XMLsgMapping2cossCompleted(this, new XMLsgMapping2cossCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void BossGatewayCompletedEventHandler(object sender, BossGatewayCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BossGatewayCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BossGatewayCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ynDevCompletedEventHandler(object sender, ynDevCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ynDevCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ynDevCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void sgMappingCompletedEventHandler(object sender, sgMappingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sgMappingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sgMappingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void devClusterCompletedEventHandler(object sender, devClusterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class devClusterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal devClusterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetSSLBasicPackageCompletedEventHandler(object sender, GetSSLBasicPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetSSLBasicPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetSSLBasicPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateAccWithPkgCompletedEventHandler(object sender, CreateAccWithPkgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAccWithPkgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAccWithPkgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void setUserCompletedEventHandler(object sender, setUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void removeUserCompletedEventHandler(object sender, removeUserCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class removeUserCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal removeUserCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void setMasterCompletedEventHandler(object sender, setMasterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setMasterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setMasterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void CreateAccountCompletedEventHandler(object sender, CreateAccountCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateAccountCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CreateAccountCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void sgToDeviceCompletedEventHandler(object sender, sgToDeviceCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class sgToDeviceCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal sgToDeviceCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AddPackageCompletedEventHandler(object sender, AddPackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AddPackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AddPackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void RemovePackageCompletedEventHandler(object sender, RemovePackageCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RemovePackageCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RemovePackageCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void ReadAccountSubscriberGroupsCompletedEventHandler(object sender, ReadAccountSubscriberGroupsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ReadAccountSubscriberGroupsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ReadAccountSubscriberGroupsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetAccountbyDeviceExternalIdCompletedEventHandler(object sender, GetAccountbyDeviceExternalIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAccountbyDeviceExternalIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAccountbyDeviceExternalIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void log_GetDeviceSGCompletedEventHandler(object sender, log_GetDeviceSGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class log_GetDeviceSGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal log_GetDeviceSGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void log_GetUserCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void AccountDetailsCompletedEventHandler(object sender, AccountDetailsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class AccountDetailsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal AccountDetailsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void log_getAccDetailsCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void GetDupSGCompletedEventHandler(object sender, GetDupSGCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDupSGCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDupSGCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void xboxMPFCompletedEventHandler(object sender, xboxMPFCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class xboxMPFCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal xboxMPFCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void stbToPurchaseCompletedEventHandler(object sender, stbToPurchaseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class stbToPurchaseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal stbToPurchaseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void QuanTuenCompletedEventHandler(object sender, QuanTuenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class QuanTuenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal QuanTuenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void getMSWDSeqCompletedEventHandler(object sender, getMSWDSeqCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getMSWDSeqCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getMSWDSeqCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void tttCompletedEventHandler(object sender, tttCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class tttCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal tttCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    public delegate void XMLsgMapping2cossCompletedEventHandler(object sender, XMLsgMapping2cossCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.17929")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class XMLsgMapping2cossCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal XMLsgMapping2cossCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591